apiVersion: apps/v1
kind: Deployment
metadata:
  name: bus-booking
spec:
  replicas: 4
  selector:
    matchLabels:
      app: bus-booking
  template:
    metadata:
      labels:
        app: bus-booking
    spec:
      containers:
      - name: cont-1
        image: nagarjuna734/bus-booking:bus-booking_V1
        ports:
        - containerPort: 3000
